pref("extensions.quickdialtool.backgroundCustomColor", "");
pref("extensions.quickdialtool.backgroundColor", "#CAD2D7");
pref("extensions.quickdialtool.standardColor", "");
pref("extensions.quickdialtool.backgroundImage", "");
pref("extensions.quickdialtool.usebackgroundColor", false);
pref("extensions.quickdialtool.usebackgroundImage", false);
pref("extensions.quickdialtool.usesearch", true);
pref("extensions.fastdial.options", "{ \"width\": 4, \"height\": 3, \"thumbWidth\": 200, \"fixed\": false }");
pref("extensions.fastdial.enable", false);
pref("extensions.quickdialtool.nwsMenuhidden", true);
pref("extensions.quickdialtool.nwsSidebar", false);
pref("extensions.quickdialtool.nwsMenuname", "National Weather Service");
pref("extensions.quickdialtool.nwsURL", "https://mobile.weather.gov/");
pref("extensions.quickdialtool.darkskyMenuhidden", true);
pref("extensions.quickdialtool.darkskySidebar", false);
pref("extensions.quickdialtool.darkskyMenuname", "Dark Sky");
pref("extensions.quickdialtool.darkskyURL", "https://darksky.net/");
pref("extensions.quickdialtool.Menuhidden23", true);
pref("extensions.quickdialtool.Menuhidden24", true);
pref("extensions.quickdialtool.Menuhidden25", true);
pref("extensions.quickdialtool.Sidebar23", false);
pref("extensions.quickdialtool.Sidebar24", false);
pref("extensions.quickdialtool.Sidebar25", false);
pref("extensions.quickdialtool.Menuname23", "");
pref("extensions.quickdialtool.Menuname24", "");
pref("extensions.quickdialtool.Menuname25", "");
pref("extensions.quickdialtool.URL23", "");
pref("extensions.quickdialtool.URL24", "");
pref("extensions.quickdialtool.URL25", "");
